services:
  - type: web
    name: overhead
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: overhead-cache
          property: connectionString

  - type: keyvalue
    name: overhead-cache
    plan: free
    ipAllowList: []
